spring:
  application:
    name: restaurant_table_reservation

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://localhost:9091/restaurant_table_reservation?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:./restaurant-table-reservationdb
#    username: sa
#    password: 1234
